### ISSUE TITLE
Error while getting Tweets removed for Copyright

### ISSUE THREAD

**Issue by Tazeg** [haccer/tweep#19] opened 2018-02-05 09:13 UTC
The command was :

./tweep.py -u <user> --csv -o tweets.csv

`Traceback (most recent call last):
  File "./tweep.py", line 145, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "./tweep.py", line 115, in main
    feed, init = await getTweets(init)
  File "./tweep.py", line 72, in getTweets
    datestamp = tweet.find("a", "tweet-timestamp")["title"].rpartition(" - ")[-1]
TypeError: 'NoneType' object is not subscriptable
`

**Comment by haccer** [comment] 2018-02-05 15:16
Looks like you forgot to add a user

**Comment by Tazeg** [comment] 2018-02-05 15:54
No i did not forgot the user. The error came while doing the job.
The command i used is :
`./tweep.py -u <user> --csv -o tweets.csv` but `<user>` must be in HTML in my message up.

**Comment by haccer** [comment] 2018-02-22 01:10
I'm unable to reproduce this issue. Are you still having trouble? 
From looking at the error, it appears to have occurred while trying to parse the date.
Could you perhaps provide the username that resulted in this error?

**Comment by Tazeg** [comment] 2018-02-23 19:00
@realdonaldtrump

**Comment by haccer** [comment] 2018-02-23 20:47
Okay thank you. I’ll take a look at this tonight.

**Comment by haccer** [comment] 2018-02-24 19:28
I figured out the source of the issue,

![](https://i.imgur.com/ClarLeF.png)

Tweep breaks when there's a Tweet "withheld in response to a report from the copyright holder."

Working on a fix.

**Comment by haccer** [comment] 2018-02-24 20:03
Fixed in recent [commit](https://github.com/haccer/tweep/commit/30116127fdeba26026129ed1dc614a9a998b292a).

Added a filter for copyright tweets. Retested against Donald Trump's Twitter to confirm fix.

**Closed by haccer** 2018-02-24 20:03 UTC
Labels: bug
