### ISSUE TITLE
Limits >= 20 doesn't work, Tweets option doesn't exist 

### ISSUE THREAD

**Issue by LinkerAX** [haccer/tweep#47] opened 2018-03-20 22:12 UTC
### Initial Check 
Make sure you've checked the following.

- [] Python version is 3.5 or higher. **True**
- [] Using the latest version of Tweep. **True**

### Command
python tweep.py -u {account} --limit 20

### Description of Issue
For account = "binance":
Only 5 latest tweets get parsed and one tweet from 2017 from person @bi_15174872228
![image](https://user-images.githubusercontent.com/33063792/37685424-8287e4ba-2ca4-11e8-8d6d-287af4b93724.png)

For account = "vergecurrency":
If --limit < 20 tweets get parsed infinitely(all of them)
If --limit >= 20 exactly 20 tweets get parsed no matter the --limit value

### OS Details
Windows 8.1 64

**UPD**
Just noticed that `tweets` in line 180 doesn't exist therefore --tweets doesn't work

**Comment by LinkerAX** [comment] 2018-03-20 22:17
Just noticed that `tweets` in line 180 doesn't exist and therefore --tweets doesn't work

**Comment by haccer** [comment] 2018-03-21 03:34
Thank you for your input.

## Binance
Tweep is fine, Twitter is not:
- [https://twitter.com/search?f=tweets&vertical=default&q=from%3Abinance&src=typd](https://twitter.com/search?f=tweets&vertical=default&q=from%3Abinance&src=typd)

Not much I can really do there.

## Limits
I'll address that issue tomorrow, likely caused by rewrite or pull request.

## Tweets
Fixed. Thanks for catching that!

**Comment by haccer** [comment] 2018-03-29 20:22
Sorry I just got to this now, bug was fixed in this [commit](https://github.com/haccer/tweep/commit/2b2a1b337ecf49a615c2dbcb4beb56c8a8b153d5) due to the conditional being less than or equal to, which was corrected to greater than or equal to.

**Closed by haccer** 2018-03-29 20:22 UTC
Labels: bug
